[project]
name = "airplane_simple-chatbot"
version = "0.0.1"
description = "a simple airplane chatbot"
author = "parsa"

[observability]
type = "phoenix"
host_type = "local"

[ml]
type = "llm"
provider = "local"
model_dir = "./models"

[ml.serve]
port = 8080
model_name = "qa_model"
alias = "champion"
tracking = "mlflow"
serving_tech = "llamacpp"

[ml.litellm]
model = "openai/custom"
api_key = "none"
api_base = "http://localhost:8080/v1"
temperature = 0.5
max_tokens = 1000
top_p = 1.0
top_k = 50

[project.dependencies.airplane_simple_retriever]
name = "airplane_simple_retriever"
directory = "./.appdeps/airplane_simple_retriever"
local = true
